# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cM5h8m7uNQAYbOddQGgX-Wx3onir4lqm
"""

import streamlit as st
import pandas as pd
import numpy as np
import pickle
from sklearn.preprocessing import LabelEncoder, StandardScaler

# ----------------------------
# Load trained model
# ----------------------------
with open("model_bagus.pkl", "rb") as f:
    model = pickle.load(f)

# ----------------------------
# Encoder mapping (disesuaikan dengan data Obesity)
# ----------------------------
label_encoders = {}
label_cols = ['Gender', 'family_history_with_overweight', 'FAVC', 'CAEC', 'SMOKE', 'SCC', 'CALC', 'MTRANS']

encoder_maps = {
    'Gender': ['Female', 'Male'],
    'family_history_with_overweight': ['no', 'yes'],
    'FAVC': ['no', 'yes'],
    'CAEC': ['no', 'Sometimes', 'Frequently', 'Always'],
    'SMOKE': ['no', 'yes'],
    'SCC': ['no', 'yes'],
    'CALC': ['no', 'Sometimes', 'Frequently', 'Always'],
    'MTRANS': ['Automobile', 'Bike', 'Motorbike', 'Public_Transportation', 'Walking']
}

for col, classes in encoder_maps.items():
    le = LabelEncoder()
    le.fit(classes)
    label_encoders[col] = le

# ----------------------------
# Streamlit UI
# ----------------------------
st.title("Prediksi Tingkat Obesitas")
st.markdown("Masukkan data berikut untuk memprediksi kategori obesitas Anda.")

# Input
gender = st.selectbox('Jenis Kelamin', encoder_maps['Gender'])
age = st.slider('Usia', 10, 100, 25)
height = st.slider('Tinggi Badan (m)', 1.3, 2.2, 1.7)
weight = st.slider('Berat Badan (kg)', 30, 200, 70)
family_history = st.selectbox('Riwayat keluarga overweight?', encoder_maps['family_history_with_overweight'])
favc = st.selectbox('Sering makan makanan tinggi kalori?', encoder_maps['FAVC'])
fcvc = st.slider('Frekuensi konsumsi sayur (1-3)', 1, 3, 2)
ncp = st.slider('Jumlah makan besar per hari (1-4)', 1, 4, 3)
caec = st.selectbox('Ngemil?', encoder_maps['CAEC'])
smoke = st.selectbox('Merokok?', encoder_maps['SMOKE'])
scc = st.selectbox('Kontrol kalori?', encoder_maps['SCC'])
ch2o = st.slider('Konsumsi air harian (1-3 liter)', 1, 3, 2)
faf = st.slider('Frekuensi aktivitas fisik (0-3)', 0, 3, 1)
tue = st.slider('Waktu menatap layar/hari (0-2 jam)', 0, 2, 1)
calc = st.selectbox('Konsumsi alkohol?', encoder_maps['CALC'])
mtrans = st.selectbox('Transportasi utama?', encoder_maps['MTRANS'])

# Buat dataframe
input_df = pd.DataFrame({
    'Gender': [gender],
    'Age': [age],
    'Height': [height],
    'Weight': [weight],
    'family_history_with_overweight': [family_history],
    'FAVC': [favc],
    'FCVC': [fcvc],
    'NCP': [ncp],
    'CAEC': [caec],
    'SMOKE': [smoke],
    'SCC': [scc],
    'CH2O': [ch2o],
    'FAF': [faf],
    'TUE': [tue],
    'CALC': [calc],
    'MTRANS': [mtrans]
})

# Label encoding
for col in label_cols:
    input_df[col] = label_encoders[col].transform(input_df[col])

# Standarisasi
numerical_cols = ['Age', 'Height', 'Weight', 'FCVC', 'NCP', 'CH2O', 'FAF', 'TUE']
scaler = StandardScaler()
input_df[numerical_cols] = scaler.fit_transform(input_df[numerical_cols])

# ----------------------------
# Prediksi
# ----------------------------
if st.button("Prediksi"):
    try:
        result = model.predict(input_df)
        st.success(f"Hasil Prediksi Tingkat Obesitas: **{result[0]}**")
    except Exception as e:
        st.error("Gagal melakukan prediksi.")
        st.error(str(e))